#markdown: kramdown
#kramdown:
#    input: GFM

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]


# user defined vars

homepage: http://simulatedsimian.github.io/
homepagetext: Home






